name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pages directories
        run: |
          mkdir -p out/CVE-2016-9086
          mkdir -p out/CVE-2021-22205
          cp -r CVE-2016-9086/* out/CVE-2016-9086/
          cp -r CVE-2021-22205/* out/CVE-2021-22205/

      - uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Delete Pages Artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: out
